//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHospital
    {
        public int HospitalID { get; set; }
        public string HospitalName { get; set; }
        public string Adress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Owns { get; set; }
        public int Flors { get; set; }
        public int Levels { get; set; }
        public bool Balcony { get; set; }
        public bool Yard { get; set; }
        public int AmbulancePoint { get; set; }
        public int InvalidPoint { get; set; }
    }
}
